### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by mash55** [poblabs/weewx-belchertown#16]
Yeah, I am back... trying to get real-time updates working. Weather-station and weewx server is in remote location. I do not have remote access to the router for port forwarding. I tried to set it up with a public broker for now (test.mosquitto.org).
Posting data seems to work. Log is showing:

`Oct  2 17:35:39 spyserver weewx[3324]: restx: MQTT: Published record 2018-10-02 17:35:40 MDT (1538523340)
Oct  2 17:35:42 spyserver weewx[3324]: restx: MQTT: Published record 2018-10-02 17:35:42 MDT (1538523342)
`

I can also see real time data when using mosquitto client subscribing to test.mosquitto.org

However, the Webpage (Belchertown skin) is telling me: The weather station is offline. Real time updates are not available. Please try again later!

Here the relevant entries in weewx.conf:

`[[MQTT]]
        server_url = mqtt://test.mosquitto.org:1883
        topic = mashNET
        unit_system = US
        binding = archive, loop
        aggregation = aggregate

    [[Belchertown]]
        HTML_ROOT = /var/weewx/reports
        skin = Belchertown
        [[[Extras]]]
            logo_image = http://schnizer.net/wx_banner.png
            footer_copyright_text = mashNET - schnizer.net
            earthquake_enabled = 1
            earthquake_maxradiuskm = 1000
            earthquake_stale = 10800
            highcharts_enabled = 1
            forecast_enabled = 1
            darksky_secret_key = *************************
            mqtt_enabled = 1
            mqtt_host = test.mosquitto.org
            mqtt_port = 1883
            mqtt_topic = mashNET
            disconnect_live_visitor = 180000
            radar_html =`

Any idea what I am doing wrong?
Thanks
Matt

**Comment by 41south** [comment]
Topic mashnet/# in the conf should fix it

**Comment by mash55** [comment]
Thanks, are you referring to the [[Belchertown]] section? 
mqtt_topic = mashNET/#

or the MQTT section under [StdRESTful]? or both?

**Comment by 41south** [comment]
Sorry just in the Belchertown section, it's the 'receive' side that needs
the /#, it basically says read everything in the topic

**Comment by mash55** [comment]
Thanks for the clarification. Unfortunately still no luck.  Here my last settings again:

[[MQTT]]
        server_url = mqtt://test.mosquitto.org:1883
        topic = mashNET
        unit_system = US
        binding = archive, loop
        aggregation = aggregate
-------------------------------------------------------
[[Belchertown]]
        HTML_ROOT = /var/weewx/reports
        skin = Belchertown
        [[[Extras]]]
            logo_image = http://schnizer.net/wx_banner.png
            footer_copyright_text = mashNET - schnizer.net
            earthquake_enabled = 1
            earthquake_maxradiuskm = 1000
            earthquake_stale = 10800
            highcharts_enabled = 1
            forecast_enabled = 1
            darksky_secret_key = *******************
            mqtt_enabled = 1
            mqtt_host = test.mosquitto.org
            mqtt_port = 1883
            mqtt_topic = mashNET/#
            disconnect_live_visitor = 180000
            radar_html = blah blah

Could it be related to the fact that I am still running a development version (version 0.8rc1)?

**Comment by poblabs** [comment]
No, 0.8rc1 shouldn't affect MQTT's settings. 

When you view your syslog, does weewx say it's publishing records? For example mine says this:

```
Oct  3 11:45:29 zeus weewx[29345]: restx: MQTT: Published record 2018-10-03 11:45:29 EDT (1538581529)
Oct  3 11:45:31 zeus weewx[29345]: restx: MQTT: Published record 2018-10-03 11:45:31 EDT (1538581531)
Oct  3 11:45:34 zeus weewx[29345]: restx: MQTT: Published record 2018-10-03 11:45:34 EDT (1538581534)
```

**Comment by poblabs** [comment]
Oh sorry, you already said that :)  Helps if I READ....

Ok, so using the mosquitto_sub client, let's see if we see data:

`mosquitto_sub -h test.mosquitto.org -p 1883 -t mashNET/#`

So far, I don't see any data yet.... are you still publishing?

**Comment by mash55** [comment]
Yep, I see data when using mosquitto_sub and NO, I turned it off... I can turn it back on if you like...

**Comment by poblabs** [comment]
Please turn it back on, I'll see if I can get some testing on my side to compare settings.

**Comment by mash55** [comment]
OK, it's back on... website URL is http://cabin.schnizer.com:8892/

**Comment by poblabs** [comment]
Worked for me! In order to have the MQTT data publish to a webpage, we need to use something called websockets. 

test.mosquitto.org's information is here:
![image](https://user-images.githubusercontent.com/3484775/46423599-e9234700-c704-11e8-8b35-69022f5cab40.png)

So I setup my config to look like this:
```
    [[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/belchertown
        skin = Belchertown
        [[[Extras]]]
            mqtt_enabled = 1
            mqtt_host = test.mosquitto.org
            mqtt_port = 8081
            mqtt_ssl = 1
            mqtt_topic = mashNET/loop
```

And after a `sudo service weewx restart` and a `sudo wee_reports`, I get this:

![image](https://user-images.githubusercontent.com/3484775/46423648-06581580-c705-11e8-8a00-4ef5bc28b461.png)

So I'm using the SSL version of the websockets. Their non-encrypted port 8080 wasn't working for me. 

Give it a try

**Comment by mash55** [comment]
Yeah, that works in my environment too - thanks a bunch. When I move the broker inhouse, do I have to fiddle with the ports/ssl as well? Or is the encountered issue related to the test platform I use with mosquitto.org?

Thanks again for your help.
Matt

**Comment by poblabs** [comment]
All depends on what you want to do. If you want the webpage to be internal and only you see it at home, then no you won't have to mess with ports or SSL. 

If you want outside visitors be able to see your site and data, then you will have to fiddle with ports and making them available through your router's firewall through port forwarding. 

The SSL is at your discretion since this is weather data and not sensitive data. 

[I've written a how-to guide on getting an MQTT broker setup](https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/). Hopefully it's able to offer some more help.

**Comment by mash55** [comment]
Thanks, I followed your write-up and it seems to work as far as I can test remotely. Have to drive up to the station to make changes to router (port forwarding) to test with website (skin) and move broker inhouse.
I might be back with new problems ;)
Best
Matt

**Comment by poblabs** [comment]
Ah, if your station is remote from your house, you'll need to fiddle with ports for INBOUND MQTT as well at home. 

I assume your station has an internet connection somewhere and your broker will be at home? If so...

So at the station you may not need to forward anything (unless your MQTT broker will live there?), since it should be able to send MQTT just fine without and fiddling. 

At home you may need to port forward 1883 and 9000 for MQTT and websockets so the station can publish to 1883 and clients to the website can get that data on 9000

FYI - The 9000 is arbitrary and can be anything, same with 1883 but 1883 is the commonly used port for MQTT.

**Comment by mash55** [comment]
I am actually planning to have weewx and the broker on the same system (remote) to reduce data traffic. With ~2sec update I expect about 1.5GB of traffic per month (if my math is correct). Since remote location has limits on the internet connection I prefer to have the broker on the same LAN.

**Comment by poblabs** [comment]
That makes sense, but don't forget about live data usage for website visitors. That'll go against your bandwidth as well.

**Comment by poblabs** [comment]
Closing this issue. Let me know if you need more help.

**Comment by mash55** [comment]
Not right now... it is working with external broker. Next time I am up at the cabin (~2 weeks) I will take a stab at moving to my own broker. Will ask for help if experience problems. Feel free to close.
