### ISSUE TITLE
Issues with METRIC mode

### ISSUE THREAD

**Issue by KasturiNagarWeather** [poblabs/weewx-belchertown#8]
Hi Pat,

I am seeing multiple issues when using Belchertown skin with METRIC mode.

1) The highcharts day graphs - only the axes labels changed to metric, the data remains in Imperial units.
2)  The records page has data remaining at imperial in few places

Largest Daily Temperature Range | 26.7 °C | May 14, 2018(Min: 62.5 °C - Max: 89.2 °C ) | May 14, 2018(Min: 62.5 °C - Max: 89.2 °C ) | 26.7 °C
-- | -- | -- | -- | --
Smallest Daily Temperature Range | 5.6 °C | January 17, 2018(Min: 61.9 °C - Max: 67.5 °C ) | January 17, 2018(Min: 61.9 °C - Max: 67.5 °C ) | 5.6 °C

3) The temperature graphs for weekly, monthly and yearly are fine but the rain graphs are still in inches. Need to check wind and other data.

See similar issues fo in my page and Colin's page

My page : http://bedi.co.in:15000/pc-aws/weather/belchertown/

Colin's page : http://41south.net.nz

Regards,
Praveen

**Comment by KasturiNagarWeather** [comment]
Hi Pat,

Yes I do have metric setup.
Attached screen shot of yearly rain from Colin page

This doesn't match with http://41south.net.nz/reports/?yr=2018&mo=08

Same issue for me too.

Regards,
Praveen

**Comment by KasturiNagarWeather** [comment]
Yes Colin's page doesn't have the issue on records page, has only for some
graphs.

One difference maybe

My archive db is in imperial and needs to be converted to metric by the skin
Colin is running a simulator, not sure what his archive db units are.

Maybe the issue pops when converting ?

Regards,
Praveen

**Comment by poblabs** [comment]
Maybe.  The NOAA reports are from built-in weewx. I did not modify those, just copy/paste. So it could be something with the database.

**Comment by KasturiNagarWeather** [comment]
The NOAA records work fine for me. Its the graphs that are having issues.

**Comment by KasturiNagarWeather** [comment]
Updated to 0.7 version. Now all day weekly monthly yearly graphs are in imperial instead of metric. The labels are also imperial. Looks like the units dont get passed to Highcharts extension?
The issue now seems more explainable compared to yesterday.

The issue in Records page also still persists. I know you did not do anything to fix it - just an FYI.

**Comment by KasturiNagarWeather** [comment]
Adding Units to Highcharts section also in weewx.conf made the temperature plots in weekly, monthly and yearly fine (day is still wrong). The rain and wind plots are still off in all graphs.

Looks like some parts of code are not checking for Units.

One observation was that belchertown_highcharts.py looks for self,generator.skin_duct['Units'] instead of belchertown_skin_duct.

**Comment by KasturiNagarWeather** [comment]
Fixed temperature graphs issues. There are a bunch of converts missing in belchertwon_highchartsSearchX.py. Attached my modified file.

However I am stuck at adding convert for rain as the fetch is slightly different for it. If I add a convert on rain lookup variable I get error in conversion. Guessing the vector returned doesnt have the units for convert function. Gary should be able to fix it easily I guess.

[belchertown_highchartsSearchX.py.txt](https://github.com/poblabs/weewx-belchertown/files/2364134/belchertown_highchartsSearchX.py.txt)

**Comment by KasturiNagarWeather** [comment]
Conversions missing in belchertown.py for max /min temperature range too. Again not sure how to convert them. If queried using getsqlvectors then convert works. If queried through gensql then convert errors out.

**Comment by 41south** [comment]
Have just upgraded to 0.7 and all charts have imperial axis at the left but metric data in the charts. Was the above a fix for this?

**Comment by 41south** [comment]
Barometer is stuck in inhg for all Highcharts no matter what the settings are in skin.conf or weewx.conf

**Comment by 41south** [comment]
The barometer graphs are definitely a new problem, they worked fine before 0.7. The left axis issue I'm not 100% sure about, I think it's new, I'm sure I would have noticed it before

**Comment by KasturiNagarWeather** [comment]
Are you sure the graphs have metric data? There is a bunch of converts
missing in highcharts Python code.

**Comment by poblabs** [comment]
Interesting. I didn't touch barometer in any of my 0.6 ---> 0.7 updates. I'll have to take a look

**Comment by poblabs** [comment]
I'm not sure, to be honest, as stated the code is Gary's and I've forked it and modified it slightly to include it with the theme. 

Since this is a hobby and I work on this in my free time, I'll take a look when time allows. If you spot a fix beforehand, let me know.

**Comment by 41south** [comment]
I could go back to 0.6, for me it was working better than 0.7 unfortunately. My coding skills are nowhere near good enough to look for fixes for this so I'll just have to sit back and wait :)

**Comment by 41south** [comment]
Praveen talks about a bout a bunch of conversions missing - and his site does have metric left axis. @KasturiNagarWeather have you fixed some of the issues or are they just on my site?

**Comment by poblabs** [comment]
@41south 0.6 was working better? How so? I had been testing 0.7 quite a bit, and even had a beta user test it. So far so good with speed ups on graph and page generation. Really the big change was splitting the skins apart to make it faster. Changes with the graphs were timespan changes - not units. 

As I understand it, highcharts is getting the data from the database as raw values. 

Let's try this. I bet we have to tell the new `Highcharts_Belchertown` skin to use Metric as well. Take the [METRIC conversion you have for the `Belchertown` skin](https://github.com/poblabs/weewx-belchertown#using-metric), and copy/paste it to the `Highcharts_Belchertown` skin. Restart weewx. Does it update?

Also, I think Praveen has a database that is half setup for METRIC, and half setup for US - based on my understanding. That could be part of the problem right there for Praveen... a mix mosh database will cause all kinds of issues that I can't begin to support (I'm not a core dev of weewx). 

If we look at this bit from weewx.conf:

```
[StdConvert]
    
    # The target_unit affects only the unit system in the database. Once
    # chosen it cannot be changed without converting the entire database.
    # Modification of target_unit after starting weewx will result in
    # corrupt data - the database will contain a mix of US and METRIC data.
    #
    # The value of target_unit does not affect the unit system for
    # reporting - reports can display US, Metric, or any combination of units.
    #
    # In most cases, target_unit should be left as the default: US
    #
    # In particular, those migrating from a standard wview installation
    # should use US since that is what the wview database contains.
    
    # DO NOT MODIFY THIS VALUE UNLESS YOU KNOW WHAT YOU ARE DOING!
    target_unit = US    # Options are 'US', 'METRICWX', or 'METRIC'
```

I wonder what this is set for in both of your setups?

And let me know if applying the metric to the `Highcharts_Belchertown` helps.

**Comment by poblabs** [comment]
Also you can make the metric change to the skin settings within weewx.conf so you don't lose the changes on upgrades 😄

**Comment by KasturiNagarWeather** [comment]
Pat,

Just confirmed that my modified code is attached in earlier post. You can
diff it with your original. Need to add a few more converts for rain and
records (max min temperature range, rain in records etc).

Regards,
Praveen

**Comment by 41south** [comment]
Progress

All graphs now have metric axis - except temp which has stayed at deg F

Go have sleep - I'll just double check I got all the units right

**Comment by 41south** [comment]
I did have them all set in weewx.conf as well, so that was being overridden by the skin.conf?

**Comment by poblabs** [comment]
@KasturiNagarWeather I'll check it tomorrow as time allows and run my tests on it. It needs to be able to satisfy metric and imperial. 

@41south Progress is good. And other way around... any options in skin.conf will be ignored if it exists in weewx.conf..... weewx.conf is the master config file.

**Comment by 41south** [comment]
Found the missing one - I missed group_temperature

I also hadn't put them under Highcharts_Belchertown in weewx.conf, I'd only added them to the primary Belchertown settings

Thanks Pat!

**Comment by poblabs** [comment]
Check the changes in commit https://github.com/poblabs/weewx-belchertown/commit/1f8af255c8ae6f05332e3ad961bb7bc86a4ffeff - I had a user test this for me and he's indicated it's fixed the year rain graph being wrong. I also added a line graph in the chart for total rain yearly. 

Feel free to test and let me know.

**Comment by 41south** [comment]
Pat can I just download and copy in those 3 files to update that?

Colin

**Comment by poblabs** [comment]
No there's some new options too that you will need.

If you look at the recent commits, or download the master branch and copy
everything in bin/user and skins folders over it would work.

Have a backup of everything just in case.

**Comment by KasturiNagarWeather** [comment]
Finally got some time to try latest commits.

The rain still has convert missing. If you check

https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown_highchartsSearchX.py

Temperature and wind has convert function called. Rain doesnt have convert called. Hence if database has it in inches but I want to display in mm, it does not work.

**Comment by KasturiNagarWeather** [comment]
Similar issue with rain data in records page also.

**Comment by ebonzl** [comment]
Wow so glad there is work going on to fix this, definitely the best skin I have found by far -  I have a WS1000 unit and the WeeWX Database is in US units. As mentioned above, all looks great except for the graphs - Daily Rain - US scale and units,  (however the weekly/monthly/annual looks OK), Hourly rainfall (US Inches) - all the other rainfall graphs in inches also. Another quirk is the Annual wind direction is pretty much all due north (?) however not sure if that is the skin or the way the data is aggregated.

My test site https:\\wwx.centratus.com\weewx 

Regards all,

Ian

**Comment by poblabs** [comment]
@KasturiNagarWeather @ebonzl Hey guys, finally had some time to look at the **rain graphs only**. 

I'm not sure why day is wrong for you but week/month/year are working because it's the same code. 

Regardless, check out the commit https://github.com/poblabs/weewx-belchertown/commit/5ac7b8d7165737c2f3ffd7dcfb22fa6fbcb0801d I just pushed. It adds a conversion on the rain and rainRate values. Thanks to Gary's code for having that in there - so I was able to spot what I missed quickly. 

To test it, please download the file from here: https://github.com/poblabs/weewx-belchertown/blob/5ac7b8d7165737c2f3ffd7dcfb22fa6fbcb0801d/bin/user/belchertown_highchartsSearchX.py 

Click on the `Raw` link, copy and paste the contents into your `bin/user/belchertown_highchartsSearchX.py`. Then [make sure you also have your units set correctly in the config files](https://github.com/poblabs/weewx-belchertown#using-metric), and finally restart weewx for the changes to apply. 

You should see the updates within 3 interval periods.

Before I move on to the Records page problems, I want to make sure the graphs are looking OK. Let me know.

**Comment by ebonzl** [comment]
Just tested your file, I get the foloowing error:

Mon Oct  1 12:40:25 2018 user.debug weewx[972]: manager: Daily summary version is 2.0
Mon Oct  1 12:40:25 2018 user.crit weewx[972]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Mon Oct  1 12:40:25 2018 user.crit weewx[972]:         ****  Module 'user.belchertown' has no attribute 'getData' when searching for 'user.belchertown.getData'
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****  Traceback (most recent call last):
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****      obj.start()
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****      self.run()
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 155, in run
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****      self.initExtensions(gen_dict[section_name])
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 197, in initExtensions
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****      class_ = weeutil.weeutil._get_object(x)
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1140, in _get_object
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****      raise AttributeError("Module '%s' has no attribute '%s' when searching for '%s'" % (mod.__name__, part, module_class))
Mon Oct  1 12:40:25 2018 user.info weewx[972]:         ****  AttributeError: Module 'user.belchertown' has no attribute 'getData' when searching for 'user.belchertown.getData'
Mon Oct  1 12:40:25 2018 user.crit weewx[972]:         ****  Generator terminated
Mon Oct  1 12:40:25 2018 user.info weewx[972]: copygenerator: copied 1 files to /www/weewx

Regards,

Ian.

**Comment by poblabs** [comment]
What version are you using? This looks like an error from 0.6 or so. You
may need to upgrade to the whole master branch here since there's a lot of
changes since your last update. Or at least install 0.7 then step up to
this file.

**Comment by ebonzl** [comment]
OK, I was pretty sure I was on 0.7 already, but will do a full refresh and try again...

**Comment by ebonzl** [comment]
OK full uninstall of skin as per instructions on the upgrade page - installed v0.7, swapped out the belchertown_highchartsSearchX.py, still getting this:

Tue Oct  2 16:05:36 2018 user.debug weewx[973]: manager: Daily summary version is 2.0
Tue Oct  2 16:05:54 2018 user.crit weewx[973]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Tue Oct  2 16:05:54 2018 user.crit weewx[973]:         ****  unsupported operand type(s) for +: 'float' and 'NoneType'
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****  Traceback (most recent call last):
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      obj.start()
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      self.run()
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 158, in run
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      ngen += self.generate(section[subsection], gen_ts)
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      ngen += self.generate(section[subsection], gen_ts)
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 320, in generate
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      default_binding)
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 372, in _getSearchList
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****    File "/home/weewx/bin/user/belchertown_highchartsSearchX.py", line 993, in get_extension_list
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****      rain_count = rain_count + rain
Tue Oct  2 16:05:54 2018 user.info weewx[973]:         ****  TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
Tue Oct  2 16:05:54 2018 user.crit weewx[973]:         ****  Generator terminated
Tue Oct  2 16:05:54 2018 user.info weewx[973]: copygenerator: copied 0 files to /www/weewx

**Comment by poblabs** [comment]
@ebonzl This error means you have a NULL value in a the rain column in your database. Previously I was filtering for this in my SQL statement but this didn't carry the filter forward with the getSqlVectors. 

I've made a change in commit https://github.com/poblabs/weewx-belchertown/commit/f3c6d824c5cdfff60e33c9b89e05853db3d04aae and you can download that file here: https://github.com/poblabs/weewx-belchertown/blob/f3c6d824c5cdfff60e33c9b89e05853db3d04aae/bin/user/belchertown_highchartsSearchX.py

Try replacing your bin/user file with that one, restart weewx and let me know

**Comment by poblabs** [comment]
@dbxx Your log output looks truncated. Are you pasting the full error?

**Comment by poblabs** [comment]
Well, this might not be the right fix since the rain doesn't continue. Let me keep thinking about this one... 

Example:
![image](https://user-images.githubusercontent.com/3484775/46353632-af7e0d80-c62a-11e8-99a0-6e89f2eddccb.png)

**Comment by poblabs** [comment]
@ebonzl Ok I think the rain should work now if you have a record that's null or empty. See commit https://github.com/poblabs/weewx-belchertown/commit/cb6b1fd2bf86138f2502e4e0b5bcb55931386b3a and try the file https://github.com/poblabs/weewx-belchertown/blob/cb6b1fd2bf86138f2502e4e0b5bcb55931386b3a/bin/user/belchertown_highchartsSearchX.py in bin/user

![image](https://user-images.githubusercontent.com/3484775/46354313-4d260c80-c62c-11e8-8929-e509e261828f.png)

**Comment by poblabs** [comment]
@KasturiNagarWeather Please also try the above fix

**Comment by dbxx** [comment]
@poblabs With live data it looks fine. No such issue i mentioned before.
Rainfall graph looks also good now with your latest commit.

**Comment by dbxx** [comment]
I have still some metric issues in the records. Please see the screenshots. Some values remaining at imperial.
![rain_temp_records](https://user-images.githubusercontent.com/37770318/46364450-1ffe4c00-c676-11e8-9630-90a71de52185.png)

**Comment by poblabs** [comment]
@dbxx Yeah, I wanted to focus on the graphs first. So you had the same issue as @KasturiNagarWeather I think, and it's cleared up now?

**Comment by dbxx** [comment]
Yes i think these are the same issues.

**Comment by poblabs** [comment]
Ok great. I'll work on the records page later on today and hope to have something you can test tomorrow. Thanks for the feedback

**Comment by ebonzl** [comment]
OK - on ALL graphs, the temps are now using the correct centigrade axis scale (was previously in fahrenheit).  https://wwx.centratus.com/weewx 

As for Rain:
Daily: no rain yet today, so cannot tell
Weekly, Monthly and Yearly now have the right axis scale (mm label was already OK), but the numbers are still all off

Many thanks for you work as we are making progress tho.. :)

**Comment by poblabs** [comment]
@ebonzl great news. I see that your graphs a little out of date - it might be best for you to download a zip of this repository, stop weewx and copy the bin/user files to bin/user and the skin files to the skin directory, then restart weewx and see how it goes after a few archive intervals. 

Essentially this would upgrade you from 0.7 to 0.8rc1 (unreleased). I think it might solve some of the graph issues you're seeing. 

![image](https://user-images.githubusercontent.com/3484775/46382258-4ae99f80-c678-11e8-880c-c6801a05c67b.png)

**Comment by ebonzl** [comment]
OK done as requested now getting this unfortunately:

Wed Oct  3 17:55:25 2018 user.debug weewx[975]: reportengine: Running report Belchertown
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: reportengine: Found configuration file /home/weewx/skins/Standard/skin.conf for report Belchertown
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras']
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: manager: Daily summary version is 2.0
Wed Oct  3 17:55:26 2018 user.crit weewx[975]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  'skin'
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  Traceback (most recent call last):
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      obj.start()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.run()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 158, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      ngen += self.generate(section[subsection], gen_ts)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      ngen += self.generate(section[subsection], gen_ts)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 247, in generate
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.skin_dict['skin']))
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      val = dict.__getitem__(self, key)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  KeyError: 'skin'
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  Generator terminated
Wed Oct  3 17:55:26 2018 user.crit weewx[975]: reportengine: Caught unrecoverable exception in generator weewx.imagegenerator.ImageGenerator
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  'skin'
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  Traceback (most recent call last):
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      obj.start()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.run()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 31, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.setup()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 44, in setup
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.skin_dict['skin']))
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      val = dict.__getitem__(self, key)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  KeyError: 'skin'
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  Generator terminated
Wed Oct  3 17:55:26 2018 user.crit weewx[975]: reportengine: Caught unrecoverable exception in generator weewx.reportengine.CopyGenerator
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  'skin'
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  Traceback (most recent call last):
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      obj.start()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.run()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 417, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.skin_dict['skin']))
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      val = dict.__getitem__(self, key)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  KeyError: 'skin'
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  Generator terminated
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: reportengine: Running report Highcharts_Belchertown
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: reportengine: Found configuration file /home/weewx/skins/Highcharts_Belchertown/skin.conf for report Highcharts_Belchertown
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.belchertown_highchartsSearchX.highchartsDay', 'user.belchertown_highchartsSearchX.highchartsWeek', 'user.belchertown_highchartsSearchX.highchartsMonth', 'user.belchertown_highchartsSearchX.highchartsYear']
Wed Oct  3 17:55:26 2018 user.debug weewx[975]: manager: Daily summary version is 2.0
Wed Oct  3 17:55:26 2018 user.crit weewx[975]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  'highcharts_enabled'
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  Traceback (most recent call last):
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      obj.start()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      self.run()
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 158, in run
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      ngen += self.generate(section[subsection], gen_ts)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      ngen += self.generate(section[subsection], gen_ts)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 320, in generate
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      default_binding)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 372, in _getSearchList
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/home/weewx/bin/user/belchertown_highchartsSearchX.py", line 64, in get_extension_list
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      if belchertown_skin_dict['Extras']['highcharts_enabled'] == "0":
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****      val = dict.__getitem__(self, key)
Wed Oct  3 17:55:26 2018 user.info weewx[975]:         ****  KeyError: 'highcharts_enabled'
Wed Oct  3 17:55:26 2018 user.crit weewx[975]:         ****  Generator terminated
Wed Oct  3 17:55:26 2018 user.info weewx[975]: copygenerator: copied 0 files to /www/weewx

**Comment by poblabs** [comment]
Did you update the skin.conf in both of the skin folders from the zip file?

**Comment by ebonzl** [comment]
Repeated process - definitely replaced all files - i have made sure my [Extras] are all in weewx.conf now, but still getting errors:
Thu Oct  4 07:40:28 2018 user.debug weewx[982]: manager: Daily summary version is 2.0
Thu Oct  4 07:40:28 2018 user.crit weewx[982]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  'skin'
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  Traceback (most recent call last):
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      obj.start()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.run()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 158, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      ngen += self.generate(section[subsection], gen_ts)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      ngen += self.generate(section[subsection], gen_ts)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 247, in generate
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.skin_dict['skin']))
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      val = dict.__getitem__(self, key)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  KeyError: 'skin'
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  Generator terminated
Thu Oct  4 07:40:28 2018 user.crit weewx[982]: reportengine: Caught unrecoverable exception in generator weewx.imagegenerator.ImageGenerator
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  'skin'
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  Traceback (most recent call last):
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      obj.start()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.run()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 31, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.setup()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 44, in setup
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.skin_dict['skin']))
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      val = dict.__getitem__(self, key)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  KeyError: 'skin'
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  Generator terminated
Thu Oct  4 07:40:28 2018 user.crit weewx[982]: reportengine: Caught unrecoverable exception in generator weewx.reportengine.CopyGenerator
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  'skin'
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  Traceback (most recent call last):
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      obj.start()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.run()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 417, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.skin_dict['skin']))
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      val = dict.__getitem__(self, key)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  KeyError: 'skin'
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  Generator terminated
Thu Oct  4 07:40:28 2018 user.debug weewx[982]: reportengine: Running report Highcharts_Belchertown
Thu Oct  4 07:40:28 2018 user.debug weewx[982]: reportengine: Found configuration file /home/weewx/skins/Highcharts_Belchertown/skin.conf for report Highcharts_Belchertown
Thu Oct  4 07:40:28 2018 user.debug weewx[982]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.belchertown_highchartsSearchX.highchartsDay', 'user.belchertown_highchartsSearchX.highchartsWeek', 'user.belchertown_highchartsSearchX.highchartsMonth', 'user.belchertown_highchartsSearchX.highchartsYear']
Thu Oct  4 07:40:28 2018 user.debug weewx[982]: manager: Daily summary version is 2.0
Thu Oct  4 07:40:28 2018 user.crit weewx[982]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  'highcharts_enabled'
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  Traceback (most recent call last):
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      obj.start()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      self.run()
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 158, in run
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      ngen += self.generate(section[subsection], gen_ts)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 232, in generate
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      ngen += self.generate(section[subsection], gen_ts)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 320, in generate
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      default_binding)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 372, in _getSearchList
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/home/weewx/bin/user/belchertown_highchartsSearchX.py", line 64, in get_extension_list
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      if belchertown_skin_dict['Extras']['highcharts_enabled'] == "0":
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****    File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****      val = dict.__getitem__(self, key)
Thu Oct  4 07:40:28 2018 user.info weewx[982]:         ****  KeyError: 'highcharts_enabled'
Thu Oct  4 07:40:28 2018 user.crit weewx[982]:         ****  Generator terminated
Thu Oct  4 07:40:28 2018 user.info weewx[982]: copygenerator: copied 0 files to /www/weewx
Thu Oct  4 07:40:28 2018 user.debug weewx[982]: reportengine: Running report FTP

**Comment by poblabs** [comment]
OK great! I did find a rain graph bug that I'm working on so once that's done, then I can look into the records page

**Comment by poblabs** [comment]
You need to copy the raw code not the HTML. See above in this thread.

**Comment by KasturiNagarWeather** [comment]
![image](https://user-images.githubusercontent.com/36511283/46571244-27cc3200-c98f-11e8-9605-1b7461c8f431.png)
The rainday_cm needs to be multiplied by 10 before displaying.

**Comment by poblabs** [comment]
@KasturiNagarWeather As mentioned, I'm trying to focus on 1 problem at a time. So are your graphs fixed? 

For the MQTT, that's coming from weewx itself. I do see a typo there where it says `mm` when it's under `dayRain_cm`, so I'll fix that, but I do not believe I need to do any math since `dayRain_cm` is coming from weewx core already calculated.

**Comment by poblabs** [comment]
@KasturiNagarWeather How old is your installation? Your code looks hard-coded for `mm` and `cm` labels, but the current releases do not have that. Advise you to upgrade, at least upgrade the `index.html.tmpl`

https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L561-L564

**Comment by KasturiNagarWeather** [comment]
Mine is 0.7 with some of the latest fixes of yours post it patched in. Yes my graphs are fine. Will try upgrading the template

**Comment by KasturiNagarWeather** [comment]
> @KasturiNagarWeather As mentioned, I'm trying to focus on 1 problem at a time. So are your graphs fixed?
> 
> For the MQTT, that's coming from weewx itself. I do see a typo there where it says `mm` when it's under `dayRain_cm`, so I'll fix that, but I do not believe I need to do any math since `dayRain_cm` is coming from weewx core already calculated.

Fixed this. Needed to set units to METRICWX for MQTT.  Then the MQTT data goes out as mm instead of cm.

**Comment by poblabs** [comment]
Ok. I'm not sure of the implications on your database by switching the
units. If half of your databases the default us and then you switch it to
metricwx, not sure what that does. You might want to read the weewx user
guide on that. I can't help you with that.

**Comment by KasturiNagarWeather** [comment]
My database is entirely in US. It is just conversion that weewx does before sending out on MQTT, Earlier it was METRIC now METRICWX.

**Comment by KasturiNagarWeather** [comment]
Now the only pending issue is Records. I understand that you plan to look into it next. Will wait for updates.

**Comment by djhindley** [comment]
@dbxx Did you ever solve the records problem that you posted about on 2 Oct? I have a very similar issue.  Thanks

**Comment by poblabs** [comment]
Hey guys, sorry for the delay. I've had some changes take place in real life that required me to take a break from hobbies. Looking to get back into it soon hopefully. 

If anyone wants to take a crack at fixing it, let me know. It would be in records/index.html.tmpl. Otherwise I'll get myself back up to speed as soon as possible

**Comment by poblabs** [comment]
@dbxx I've just submitted 2 commits that try to fix some of these issues. 

If you're curious, check out https://github.com/poblabs/weewx-belchertown/commit/32df29bd9916344637e24128b0486fc18aaf6d88 and https://github.com/poblabs/weewx-belchertown/commit/def862ab653fbae4b9a7225b4d89581dcfc3556c for the changes. 

Download this file and place it into your `user/bin` and then restart weewx. 

https://github.com/poblabs/weewx-belchertown/blob/def862ab653fbae4b9a7225b4d89581dcfc3556c/bin/user/belchertown.py

*Note*: The green area is provided by weewx, so I think it should be accurate? The red areas are what I fixed. 

![image](https://user-images.githubusercontent.com/3484775/48307926-97e94d00-e525-11e8-897b-56785bb68a06.png)

**Comment by poblabs** [comment]
@djhindley This is because the 0.8rc2 has other options embedded. Grab a new copy of the skin.conf from the link below. Make sure you have a backup of your custom options if any. 

If you have options in skin.conf, [it's advised though that custom options go in to weewx.conf. ](https://github.com/poblabs/weewx-belchertown#belchertown-skin-options)

https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/skin.conf

**Comment by djhindley** [comment]
Ok. Many Thanks. Will try that.

David.

**Comment by djhindley** [comment]
I tried that and also downloaded the latest commits that I noticed Pat had done very recently regarding all time yearly rainfall records, and all seems to be working now, as per records page below. Many Thanks for addressing all these points, Pat.
![image](https://user-images.githubusercontent.com/26487824/48342058-9ecba900-e666-11e8-836d-489d5ada2443.png)

One small point to perhaps consider in future is aligning some of the records with internationally recognized climate index figures. For example, for "dry days" instead of Consecutive Days Without Rainfall, as per belchertown, CLIMDEX index no. 27 uses Consecutive Days with less than or equal to 1mm of rain, which is arguably a better measure.   See [https://www.climdex.org/indices.html] for further details.

**Comment by poblabs** [comment]
Glad everything's working! 
I'll also consider that change for dry days. Right now the code just does a count of days with no rain - so I'll have to think about how to implement the 1mm difference (since Belchertown can be used by metric and imperial). 

Closing this issue since I think all items are resolved now and will be finalized in the 0.8 release. Keep an eye on the Releases page for the upgrade package https://github.com/poblabs/weewx-belchertown/releases
